// @flow
import { processingStateType } from '../reducers/processing';

export const PROCESSING_ACCOUNT_LOADING = 'PROCESSING_ACCOUNT_LOADING';
export const PROCESSING_ACCOUNT_LOADING_FAILED = 'PROCESSING_ACCOUNT_LOADING_FAILED';
export const PROCESSING_ACCOUNT_LOADING_COMPLETE = 'PROCESSING_ACCOUNT_LOADING_COMPLETE';